apiVersion: v1
kind: Service
metadata:
  name: mongodb-service         # Nombre del servicio
  namespace: conferencia       # Namespace en el que se crea el servicio
spec:
  type: ClusterIP               # Tipo de servicio (ClusterIP crea un IP interno solo accesible desde dentro del clúster)
  ports:
    - port: 27017              # Puerto expuesto en el servicio
      targetPort: 27017        # Puerto en el que están escuchando los pods seleccionados
  selector:
    app: mongodb               # Selector para identificar los pods asociados al servicio
