---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: conferencia
spec:
  type: ClusterIP  # Puedes usar LoadBalancer si estás en un entorno compatible
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
