apiVersion: v1
kind: Service
metadata:
  name: chatappserver-svc
  namespace: conferencia
spec:
  selector:
    app: chatappserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  # type: LoadBalancer
