apiVersion: v1
kind: Service
metadata:
  name: chatappserver-svc  # Nombre del servicio
  namespace: conferencia   # Namespace donde se crea el servicio
spec:
  selector:
    app: chatappserver    # Etiqueta de selector para identificar los pods asociados al servicio
  ports:
    - protocol: TCP       # Protocolo del puerto expuesto (TCP en este caso)
      port: 8080          # Puerto en el que se expone el servicio
      targetPort: 8080    # Puerto en el que los pods del selector están escuchando
  type: LoadBalancer     # Tipo de servicio (opcional, en este caso se comenta)
